"""
Insights router – AI-generated financial analysis.

Endpoints:
    GET /insights/spending   – Spending analysis with LLM commentary.
    GET /insights/savings    – Savings recommendations considering goals.
    GET /insights/risk-score – Portfolio risk score and explanation.
"""

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from backend.database import get_db
from backend.models import Goal, Portfolio, Transaction
from backend.schemas import InsightResponse
from backend.services.llm_service import (
    calculate_risk_score,
    generate_savings_advice,
    generate_spending_insights,
)

router = APIRouter(prefix="/insights", tags=["Insights"])


def _get_spending_summary(user_id: int, db: Session) -> dict:
    """Build a spending summary dict from the user's transactions."""
    transactions = (
        db.query(Transaction)
        .filter(Transaction.user_id == user_id)
        .all()
    )

    total_income = 0.0
    total_expense = 0.0
    category_breakdown: dict[str, float] = {}

    for txn in transactions:
        if txn.transaction_type == "credit":
            total_income += txn.amount
        else:
            total_expense += txn.amount
            cat = txn.category or "Uncategorized"
            category_breakdown[cat] = category_breakdown.get(cat, 0.0) + txn.amount

    return {
        "total_income": round(total_income, 2),
        "total_expense": round(total_expense, 2),
        "net": round(total_income - total_expense, 2),
        "category_breakdown": {k: round(v, 2) for k, v in category_breakdown.items()},
        "transaction_count": len(transactions),
    }


@router.get("/spending", response_model=InsightResponse)
def get_spending_insights(
    user_id: int = Query(default=1, description="User ID"),
    db: Session = Depends(get_db),
) -> InsightResponse:
    """Generate AI-powered spending insights.

    Aggregates the user's transaction data with Pandas-style logic,
    then passes the summary to the LLM for natural-language commentary.
    """
    summary = _get_spending_summary(user_id, db)

    if summary["transaction_count"] == 0:
        return InsightResponse(
            insight_type="spending",
            content="No transactions found. Upload a bank statement to get started!",
            metadata=summary,
        )

    insights = generate_spending_insights(summary)

    return InsightResponse(
        insight_type="spending",
        content=insights,
        metadata=summary,
    )


@router.get("/savings", response_model=InsightResponse)
def get_savings_recommendations(
    user_id: int = Query(default=1, description="User ID"),
    db: Session = Depends(get_db),
) -> InsightResponse:
    """Generate savings recommendations considering financial goals.

    Combines the user's spending summary with their active goals to
    produce actionable savings advice.
    """
    summary = _get_spending_summary(user_id, db)

    goals = (
        db.query(Goal)
        .filter(Goal.user_id == user_id)
        .all()
    )
    goals_dicts = [
        {
            "name": g.name,
            "target_amount": g.target_amount,
            "current_amount": g.current_amount,
            "deadline": g.deadline.isoformat() if g.deadline else None,
            "priority": g.priority,
        }
        for g in goals
    ]

    advice = generate_savings_advice(summary, goals_dicts)

    return InsightResponse(
        insight_type="savings",
        content=advice,
        metadata={
            "summary": summary,
            "goals_count": len(goals_dicts),
        },
    )


@router.get("/risk-score", response_model=InsightResponse)
def get_risk_score(
    user_id: int = Query(default=1, description="User ID"),
    db: Session = Depends(get_db),
) -> InsightResponse:
    """Calculate and explain the portfolio risk score.

    The score is computed deterministically from asset-type weights;
    only the explanation text is generated by the LLM.
    """
    holdings = (
        db.query(Portfolio)
        .filter(Portfolio.user_id == user_id)
        .all()
    )

    if not holdings:
        return InsightResponse(
            insight_type="risk_score",
            content="No portfolio holdings found. Add assets to get a risk assessment.",
            metadata={"risk_score": 0, "risk_level": "N/A"},
        )

    portfolio_dicts = [
        {
            "asset_name": h.asset_name,
            "asset_type": h.asset_type,
            "quantity": h.quantity,
            "current_price": h.current_price,
        }
        for h in holdings
    ]

    result = calculate_risk_score(portfolio_dicts)

    return InsightResponse(
        insight_type="risk_score",
        content=result["explanation"],
        metadata={
            "risk_score": result["risk_score"],
            "risk_level": result["risk_level"],
            "asset_allocation": result["asset_allocation"],
        },
    )
